apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evo1-bdw-storage
  namespace: daai-brs-d
  labels:
    app.kubernetes.io/name: evo1-bdw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
