apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evo1-bdw-service-consumption-reader
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
