apiVersion: v1
kind: Secret
metadata:
  name: tib-daail-evo1-poc-query-engine-secret
  namespace: daai-brs-d
  labels:
    app.kubernetes.io/name: tib-daail-evo1-poc-query-engine
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: replace-me
  S3_SECRET_ACCESS_KEY: replace-me
  PG_USER: replace-me
  PG_PASSWORD: replace-me
