apiVersion: apps/v1
kind: Deployment
metadata:
  name: tib-daail-evo1-poc-query-engine
  namespace: daai-brs-d
  labels:
    app.kubernetes.io/name: tib-daail-evo1-poc-query-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tib-daail-evo1-poc-query-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tib-daail-evo1-poc-query-engine
    spec:
      containers:
        - name: duckdb
          image: docker-hub.nexus.bit.admin.ch/svabra/tib-daail-evo1-poc-query-engine:0.1.5
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4213
          resources:
            requests:
              cpu: "4"
              memory: 8Gi
            limits:
              cpu: "24"
              memory: 64Gi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: tib-daail-evo1-poc-query-engine-config
            - secretRef:
                name: tib-daail-evo1-poc-query-engine-secret
          volumeMounts:
            - name: workspace
              mountPath: /workspace
          startupProbe:
            httpGet:
              path: /info
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /info
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /info
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: workspace
          emptyDir: {}
